artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  drive_file_id: "1PMwyTlpKh-1IThTmTHRYxd1pjIsn5HYd"
  local_data_file: artifacts/data_ingestion/final-movie-data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion

data_preparation:
  root_dir: artifacts/data_preparation
  data_path: artifacts/data_transformation

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_preparation
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  model_path: artifacts/model_trainer